import {StyleSheet, Dimensions} from 'react-native';

const {width, height} = Dimensions.get('window');
const styles = StyleSheet.create({
  mainContainer: {
    display: 'flex',
    height: height * 0.7,
    padding: 30,
  },
  mainText: {
    fontSize: 26,
    color: 'white',
    fontFamily: 'Helvetica',
  },
  second: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  secondMain: {
    marginBottom: 20,
    height: height * 0.5,
  },
  header: {
    marginBottom: height * 0.05,
  },
  secondText: {
    fontSize: 22,
    color: 'white',
  },
  thirdText: {
    fontSize: 22,
    color: 'white',
    fontWeight: 'bold',
  },
  button: {
    height: 30,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: 'rgb(252,201,82)',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 10,
    marginRight: 15,
  },
  secondButton: {
    height: 30,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: 'green',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 10,
    marginRight: 15,
  },
  buttonText: {
    color: 'white',
    fontWeight: '400',
  },
  pictures: {
    width: width * 0.3,
    height: height * 0.2,
    borderRadius: 15,
    marginRight: 15,
  },
  subTitle: {
    marginBottom: 20,
    fontSize: 14,
    color: '#808080',
    fontWeight: '600',
  },
  thirdSubTitle: {
    marginBottom: 20,
    color: 'rgb(170,130,40)',
  },
  scrolls: {
    marginBottom: 20,
  },
  audioBooks: {
    backgroundColor: 'rgb(252,201,82)',
    display: 'flex',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingRight: 30,
    paddingTop: 20,
    paddingLeft: 30,
  },
  container: {
    display: 'flex',
    backgroundColor: '#484848',
    height: height + 30,
  },
  imageContainer: {
    height: height * 0.35,
    width: '100%',
    marginBottom: -30,
  },
  contentContainer: {
    height: height + 30,
    display: 'flex',
    padding: 25,
    backgroundColor: '#484848',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    overflow: 'hidden',
  },
  tags: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 15,
  },
  tagButton: {
    height: 30,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: 'green',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 10,
    marginRight: 15,
  },
  content: {
    fontSize: 14,
    color: 'whitesmoke',
    marginBottom: 20,
    textAlign: 'justify',
  },
  creditImage: {
    width: 40,
    height: 40,
    borderRadius: 25,
    marginRight: 10,
  },
  credits: {
    display: 'flex',
    flexDirection: 'row',
  },
  creditTitle: {
    color: '#d3d3d3',
  },
  authorName: {
    color: 'white',
  },
  chapter: {
    color: 'rgb(255,204,83)',
    marginBottom: 2,
  },
  cancel: {
    position: 'absolute',
    top: 15,
    display: 'flex',
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menu: {
    position: 'absolute',
    top: 30,
    display: 'flex',
    right: 30,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  back: {
    position: 'absolute',
    top: 15,
    display: 'flex',
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  info: {
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  chaptersInfo: {
    borderTopWidth: 2,
    borderTopColor: 'white',
  },
  chapterInfo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  chapterContent: {
    width: width - 70,
  },
  tagButtonAlt: {
    backgroundColor: 'rgb(255,95,88)',
  },
  mainTextSub: {
    fontSize: 22,
    marginBottom: 10,
    fontWeight: 'bold',
  },
});

export default styles;
